apiVersion: apps/v1
kind: Deployment
metadata:
  name: Test-workflow
  labels:
    app: Test-workflow
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1729122723392
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Test-workflow
  template:
    metadata:
      labels:
        app: Test-workflow
    spec:
      containers:
        - name: Test-workflow
          image: qpetraroiabugbashclusterregistry.azurecr.io/image-workflow-1729122723392:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
