apiVersion: v1
kind: Service
metadata:
  name: Test-workflow
  namespace: namespace-workflow-1729122723392
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: Test-workflow
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000