apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air
  labels:
    app.kubernetes.io/name: contoso-air
    kubernetes.azure.com/generator: devhub
  namespace: contosoair
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: contoso-air
  template:
    metadata:
      labels:
        app.kubernetes.io/name: contoso-air
        # azure.workload.identity/use: "true"  # ← Uncomment if using Azure Workload Identity
    spec:
      # serviceAccountName: sc-account-55e6584a-e547-4e50-a54c-13dfb0d0d317  # ← Uncomment if using Service Connector / Workload Identity
      containers:
        - name: contoso-air
          image: registry1738910064968.azurecr.io/contosoair:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "0.5"
              memory: "0.5Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - configMapRef:
                name: contoso-air-config
                optional: true  # ← Marked optional to prevent crash if missing
            - secretRef:
                name: sc-openai4ad46-secret
                optional: true
          livenessProbe:
            tcpSocket:
              port: 3001
          readinessProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
            successThreshold: 1
            initialDelaySeconds: 3
          startupProbe:
            tcpSocket:
              port: 3001
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - SYS_PTRACE
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: contoso-air
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: contoso-air
