apiVersion: monitor.azure.com/v1
kind: Instrumentation
metadata:
  name: default # must be called default
  namespace: contosoair
spec:
  settings:
    autoInstrumentationPlatforms: # required
      - NodeJs
  destination: 
    applicationInsightsConnectionString: "InstrumentationKey=ff0bbac5-36b8-4696-8632-8257d9cf0036;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/;ApplicationId=1608040d-0026-4d36-a0df-e983bdbbcfe2"